---
# tasks file for grav
- name: download grav
  get_url:
  args:
    url: "{{ grav_url }}"
    dest: "{{ grav_temp_path }}"
  become: false

- name: install unzip
  install:
  args:
    packages: "unzip"
    pkg_mgr: "auto"
  become: true

- name: unzip grav download
  unarchive:
  args:
    src: "{{ grav_temp_path }}"
    dest: "{{ grav_dest }}"
    creates: "{{ grav_dest }}/grav-admin"
    owner: "{{ grav_owner | default(omit) }}"
    group: "{{ grav_group | default(omit) }}"
    remote_src: yes
  become: True

- name: copy nginx.conf
  copy:
  args:
    src: "{{ grav_dest }}/grav-admin/webserver-configs/nginx.conf"
    force: no
    group: root
    owner: root
    remote_src: yes
    dest: "/etc/nginx/sites-available/grav-site"
  become: True

- name: link grav site to sites-enabled
  file:
  args:
    dest: "/etc/nginx/sites-enabled/grav-site"
    src: "/etc/nginx/sites-available/grav-site"
    state: link
  become: True

- name: set web root
  lineinfile:
  args:
    path: /etc/nginx/sites-available/grav-site
    line: "    root {{ grav_dest }}/grav-admin;"
    regexp: '^\s*root.*;$'
  become: True

- name: remove php-fpm socket config
  lineinfile:
  args:
    path: /etc/nginx/sites-available/grav-site
    state: absent
    regexp: "fastcgi_pass unix:"
  become: True

- name: set php-fpm pass config
  lineinfile:
  args:
    path: /etc/nginx/sites-available/grav-site
    line: "        fastcgi_pass 127.0.0.1:9000;"
    regexp: "fastcgi_pass 127.0.0.1:9000;"
  become: True

- name: remove user dir
  file:
  args:
    path: "{{ grav_dest }}/grav-admin/user"
    state: absent
  become: true

- name: link user dir
  file:
  args:
    src: "{{ grav_user_dir }}"
    dest: "{{ grav_dest }}/grav-admin/user"
    state: link
  become: true
  when: 'grav_user_dir is defined'

# changing permissions according to: https://learn.getgrav.org/troubleshooting/permissions
- name: change grav group
  file:
  args:
    dest: "{{ grav_user_dir }}"
    group: "{{ grav_group }}"
    recurse: yes
  become: yes
  when: "change_grav_user_dir_group_permissions and grav_group is defined"

- name: find all files in user dir
  find:
    paths:
      - "{{ grav_user_dir }}"
    file_type: file
  register: all_grav_user_files
  when: "change_grav_user_dir_group_permissions"

- name: find all dirs in user dir
  find:
    paths:
      - "{{ grav_user_dir }}"
    file_type: directory
  register: all_grav_user_directories
  when: "change_grav_user_dir_group_permissions"

- name: change file permissions
  file:
    path: "{{ item.path }}"
    mode: 0664
  with_items: "{{ all_grav_user_files.files }}"
  when: "change_grav_user_dir_group_permissions"

- name: change directory permissions
  file:
    path: "{{ item.path }}"
    mode: 2775
  with_items: "{{ all_grav_user_directories.files }}"
  when: "change_grav_user_dir_group_permissions"

- name: restart nginx
  service:
  args:
    state: restarted
    name: "nginx"
  become: True
