---
# tasks file for grav
- name: setting variable grav_user_dir
  set_fact:
    grav_user_dir_expanded: "{{ grav_user_dir | expanduser }}"

- name: check whether site already exists
  stat:
    path: "{{ grav_dest }}/{{ grav_site_name }}"
  register: site_folder

- name: including site-install (if necessary)
  include: setup-site.yml
  when: "site_folder.stat.exists"
